name: Simulation and build project

on: 
    push:
      branches: [master]
    pull_request:
      branches: [master]

env:
    artifact_path: ~/../axis-uart/project/axis_uart_top/impl/pnr/
    artifact_name: axis_uart_top.fs

jobs:
  simulation:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
            image: r0d0s/fpga_tools:latest
            run: |
              git clone https://github.com/RDSik/axis-uart.git
              cd axis-uart
              make
  build-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
            image: r0d0s/fpga_tools:latest
            run: |
              git clone https://github.com/RDSik/axis-uart.git
              cd axis-uart
              make project
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifact_name}}
          path: ${{env.artifact_path}}${{env.file_name}}
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{env.artifact_name}}
          path: ${{env.artifact_path}}