name: Verilator Simulation

on: 
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
  build-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Verilator-Iverilog-Verible-Docker
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
      - name: Copy code
        run: docker cp * ../ fpga_tools:v1.0
      - name: Run sim
        run: docker exec fpga_tools:v1.0 make
