name: Verilator Simulation

on: 
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
  build-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
            file: ./Verilator-Iverilog-Verible-Docker/Dockerfile
      - name: Copy files
        run: docker cp * ./ fpga_tools
      - name: Run sim
        run: docker exec fpga_tools make
